//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Operations_using_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string kaviya { get; set; }
        public string white_town_pondicherry { get; set; }
        public string kaviya123_gmail_com { get; set; }
        public string C10th { get; set; }
    }
}
